version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lluch_postgres
    environment:
      POSTGRES_USER: lluch_user
      POSTGRES_PASSWORD: lluch_pass
      POSTGRES_DB: lluch_regulation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lluch_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lluch_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: lluch_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      DATABASE_URL: postgresql://lluch_user:lluch_pass@postgres:5432/lluch_regulation
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: ./backend
    container_name: lluch_celery_worker
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      DATABASE_URL: postgresql://lluch_user:lluch_pass@postgres:5432/lluch_regulation
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: celery -A app.core.celery_app worker --loglevel=info

  celery_beat:
    build: ./backend
    container_name: lluch_celery_beat
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      DATABASE_URL: postgresql://lluch_user:lluch_pass@postgres:5432/lluch_regulation
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: celery -A app.core.celery_app beat --loglevel=info

  frontend:
    build: ./frontend
    container_name: lluch_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    command: npm run dev -- --host

volumes:
  postgres_data:






